#nullable enable
using System.Text;

namespace AuditLog.Generator;

public static class StringBuilderExtensions
{
    public static StringBuilder AppendAutoGeneratedHeader(StringBuilder sb, string? ns = null)
    {
        sb.AppendLine("// <auto-generated />");
        sb.AppendLine("#nullable enable");
        sb.AppendLine();
        if (!string.IsNullOrEmpty(ns) && !ns.StartsWith("<"))
        {
            sb.AppendLine($"namespace {ns};");
            sb.AppendLine();
        }
        return sb;
    }

    public static StringBuilder AppendLine(StringBuilder sb, int indent, string text)
    {
        for (var i = 0; i < indent; i++)
            sb.Append("    ");
        sb.AppendLine(text);
        return sb;
    }

    public static void AppendIndent(StringBuilder sb, int indent)
    {
        for (var i = 0; i < indent; i++)
            sb.Append("    ");
    }
}
