#nullable enable
using Microsoft.CodeAnalysis;
using System.Text;

namespace AuditLog.Generator;

internal static class CollectionEntityGenerator
{
    public static void GenerateAuditLogClass(SourceProductionContext context, ConfiguratorInfo parentConfig, CollectionConfig col)
    {
        var ns = Helpers.GetNs(parentConfig);
        var sb = new StringBuilder();
        sb.AppendLine("// <auto-generated />");
        sb.AppendLine("#nullable enable");
        sb.AppendLine();
        sb.AppendLine($"namespace {ns}");
        sb.AppendLine("{");
        sb.AppendLine($"    public sealed partial class {col.AuditLogName}");
        sb.AppendLine("    {");
        sb.AppendLine("        public long Id { get; set; }");
        sb.AppendLine();
        sb.AppendLine($"        public global::System.Guid {col.ParentKey} {{ get; set; }}");
        sb.AppendLine();
        sb.AppendLine($"        public global::System.Guid {col.ChildKey} {{ get; set; }}");
        sb.AppendLine();
        sb.AppendLine("        public AuditLog.Abstractions.AuditOperation Operacao { get; set; }");
        sb.AppendLine();
        sb.AppendLine("        public global::System.DateTimeOffset OcorridoEm { get; set; }");
        sb.AppendLine();
        sb.AppendLine("        public string? UsuarioId { get; set; }");
        sb.AppendLine();
        sb.AppendLine("        public string? CorrelationId { get; set; }");
        sb.AppendLine();
        sb.AppendLine("        public string? CamposAlteradosJson { get; set; }");
        sb.AppendLine();
        sb.AppendLine("        public long? AuditLogAnteriorId { get; set; }");
        sb.AppendLine();
        sb.AppendLine($"        public {col.AuditLogName}? AuditLogAnterior {{ get; set; }}");
        Helpers.BuildCollectionProperties(sb, col.ItemConfigs, col.ParentKey, col.ChildKey);
        sb.AppendLine("    }");
        sb.AppendLine("}");

        context.AddSource($"{ns}.{col.AuditLogName}.g.cs", sb.ToString());
    }

    public static void GenerateEntityMapClass(SourceProductionContext context, ConfiguratorInfo parentConfig, CollectionConfig col)
    {
        var ns = Helpers.GetNs(parentConfig);
        var sb = new StringBuilder();
        sb.AppendLine("// <auto-generated />");
        sb.AppendLine("#nullable enable");
        sb.AppendLine();
        sb.AppendLine("using Microsoft.EntityFrameworkCore;");
        sb.AppendLine("using Microsoft.EntityFrameworkCore.Metadata.Builders;");
        sb.AppendLine();
        sb.AppendLine($"namespace {ns}");
        sb.AppendLine("{");
        sb.AppendLine($"    public sealed class {col.AuditLogName}EntityMap");
        sb.AppendLine($"        : IEntityTypeConfiguration<{col.AuditLogName}>");
        sb.AppendLine("    {");
        sb.AppendLine($"        public void Configure(EntityTypeBuilder<{col.AuditLogName}> builder)");
        sb.AppendLine("        {");
        sb.AppendLine($"            builder.ToTable(\"{col.AuditLogName}s\");");
        sb.AppendLine();
        sb.AppendLine("            builder.HasKey(x => x.Id);");
        sb.AppendLine();
            sb.AppendLine("            builder.Property(x => x.Operacao)");
            sb.AppendLine("                .HasMaxLength(30)");
            sb.AppendLine("                .IsRequired()");
            sb.AppendLine("                .HasConversion<string>();");
        sb.AppendLine();
        sb.AppendLine("            builder.Property(x => x.UsuarioId)");
        sb.AppendLine("                .HasMaxLength(100);");
        sb.AppendLine();
        sb.AppendLine("            builder.Property(x => x.CorrelationId)");
        sb.AppendLine("                .HasMaxLength(100);");
        sb.AppendLine();
        Helpers.BuildEntityMapProperties(sb, col.ItemConfigs, col.ParentKey, col.ChildKey);
        sb.AppendLine();
            sb.AppendLine("            builder.HasOne(x => x.AuditLogAnterior)");
            sb.AppendLine("                .WithMany()");
            sb.AppendLine("                .HasForeignKey(x => x.AuditLogAnteriorId)");
            sb.AppendLine("                .OnDelete(DeleteBehavior.NoAction);");
        sb.AppendLine();
        sb.AppendLine("            builder.HasIndex(x => new");
        sb.AppendLine("            {");
        sb.AppendLine($"                x.{col.ParentKey},");
        sb.AppendLine("                x.OcorridoEm");
        sb.AppendLine("            });");
        sb.AppendLine("        }");
        sb.AppendLine("    }");
        sb.AppendLine("}");

        context.AddSource($"{ns}.{col.AuditLogName}EntityMap.g.cs", sb.ToString());
    }

    public static void GenerateDescriptorClass(SourceProductionContext context, ConfiguratorInfo parentConfig, CollectionConfig col)
    {
        var ns = Helpers.GetNs(parentConfig);
        var sb = new StringBuilder();
        sb.AppendLine("// <auto-generated />");
        sb.AppendLine("#nullable enable");
        sb.AppendLine();
        sb.AppendLine("using System;");
        sb.AppendLine("using System.Collections.Generic;");
        sb.AppendLine("using System.Text.Json;");
        sb.AppendLine("using AuditLog.Abstractions;");
        sb.AppendLine("using Microsoft.EntityFrameworkCore;");
        sb.AppendLine("using Microsoft.EntityFrameworkCore.ChangeTracking;");
        sb.AppendLine();
        sb.AppendLine($"namespace {ns}");
        sb.AppendLine("{");
        sb.AppendLine($"    internal sealed class {col.AuditLogName}Descriptor");
        sb.AppendLine($"        : IAuditDescriptor<{col.ElementName}, {col.AuditLogName}>");
        sb.AppendLine("    {");
        sb.AppendLine($"        public static readonly {col.AuditLogName}Descriptor Instance = new();");
        sb.AppendLine();
        sb.AppendLine($"        private {col.AuditLogName}Descriptor()");
        sb.AppendLine("        {");
        sb.AppendLine("        }");
        sb.AppendLine();
        sb.AppendLine($"        public {col.AuditLogName} CreateLog(");
        sb.AppendLine($"            EntityEntry<{col.ElementName}> entry,");
        sb.AppendLine("            AuditExecutionContext context)");
        sb.AppendLine("        {");
        sb.AppendLine("            var entity = entry.Entity;");
        sb.AppendLine();
        sb.AppendLine("            long? anteriorId = null;");
        sb.AppendLine();
        sb.AppendLine("            var operacao = entry.State switch");
        sb.AppendLine("            {");
        sb.AppendLine("                EntityState.Added => AuditLog.Abstractions.AuditOperation.Added,");
        sb.AppendLine("                EntityState.Modified => AuditLog.Abstractions.AuditOperation.Modified,");
        sb.AppendLine("                EntityState.Deleted => AuditLog.Abstractions.AuditOperation.Deleted,");
        sb.AppendLine("                _ => throw new InvalidOperationException($\"Unexpected entity state: {entry.State}\")");
        sb.AppendLine("            };");
        sb.AppendLine();
        sb.AppendLine("            if (entry.State != EntityState.Added)");
        sb.AppendLine("            {");
        sb.AppendLine($"                anteriorId = entry.Context.Set<{col.AuditLogName}>()");
        sb.AppendLine($"                    .Where(x => x.{col.ParentKey} == entity.{col.ParentKey} && x.{col.ChildKey} == entity.{col.ChildKey})");
        sb.AppendLine("                    .OrderByDescending(x => x.OcorridoEm)");
        sb.AppendLine("                    .Select(x => (long?)x.Id)");
        sb.AppendLine("                    .FirstOrDefault();");
        sb.AppendLine("            }");
        sb.AppendLine();
        sb.AppendLine($"            return new {col.AuditLogName}");
        sb.AppendLine("            {");
        sb.AppendLine($"                {col.ParentKey} = entity.{col.ParentKey},");
        sb.AppendLine($"                {col.ChildKey} = entity.{col.ChildKey},");
        sb.AppendLine(                "                Operacao = operacao,");
        sb.AppendLine("                OcorridoEm = context.OcorridoEm,");
        sb.AppendLine("                UsuarioId = context.UsuarioId,");
        sb.AppendLine("                CorrelationId = context.CorrelationId,");
        sb.AppendLine("                AuditLogAnteriorId = anteriorId,");
        sb.AppendLine();
        Helpers.BuildDescriptorAssignments(sb, col.ItemConfigs, "                ", col.ParentKey, col.ChildKey);
        sb.AppendLine();
        sb.AppendLine("                CamposAlteradosJson = BuildChangedPropertiesJson(entry)");
        sb.AppendLine("            };");
        sb.AppendLine("        }");
        sb.AppendLine();
        sb.AppendLine($"        public IReadOnlyList<{col.AuditLogName}> CreateChildLogs(");
        sb.AppendLine($"            EntityEntry<{col.ElementName}> entry,");
        sb.AppendLine("            AuditExecutionContext context)");
        sb.AppendLine("        {");
        sb.AppendLine($"            return global::System.Array.Empty<{col.AuditLogName}>();");
        sb.AppendLine("        }");
        sb.AppendLine();
        sb.AppendLine("        private static string BuildChangedPropertiesJson(");
        sb.AppendLine($"            EntityEntry<{col.ElementName}> entry)");
        sb.AppendLine("        {");
        sb.AppendLine("            var changed = new List<string>();");
        sb.AppendLine();
        sb.AppendLine("            if (entry.State is EntityState.Added or EntityState.Deleted)");
        sb.AppendLine("            {");
        sb.AppendLine("                changed.Add(\"*\");");
        sb.AppendLine("                return JsonSerializer.Serialize(changed);");
        sb.AppendLine("            }");
        sb.AppendLine();
        Helpers.BuildChangedPropertiesCheck(sb, col.ItemConfigs, col.ElementName, col.ParentKey, col.ChildKey);
        sb.AppendLine();
        sb.AppendLine("            return JsonSerializer.Serialize(changed);");
        sb.AppendLine("        }");
        sb.AppendLine("    }");
        sb.AppendLine("}");

        context.AddSource($"{ns}.{col.AuditLogName}Descriptor.g.cs", sb.ToString());
    }
}
