#nullable enable
using Microsoft.CodeAnalysis;
using System.Collections.Immutable;
using System.Text;

namespace AuditLog.Generator;

internal static class ExtensionGenerator
{
    public static void GenerateRegistryExtension(SourceProductionContext context, ImmutableArray<ConfiguratorInfo> configurators)
    {
        var ns = Helpers.GetNs(configurators[0]);
        var sb = new StringBuilder();
        sb.AppendLine("// <auto-generated />");
        sb.AppendLine("#nullable enable");
        sb.AppendLine();
        sb.AppendLine("using AuditLog.Abstractions;");
        sb.AppendLine();
        sb.AppendLine($"namespace {ns}");
        sb.AppendLine("{");
        sb.AppendLine("    public static partial class GeneratedAuditRegistryExtensions");
        sb.AppendLine("    {");
        sb.AppendLine("        public static AuditRegistry AddGeneratedAuditConfigurations(this AuditRegistry registry)");
        sb.AppendLine("        {");

        foreach (var config in configurators)
        {
            sb.AppendLine($"            registry.Add<{config.EntityName}, {config.AuditLogName}>(");
            sb.AppendLine($"                {config.AuditLogName}Descriptor.Instance);");

            foreach (var col in config.Collections)
            {
                sb.AppendLine($"            registry.Add<{col.ElementName}, {col.AuditLogName}>(");
                sb.AppendLine($"                {col.AuditLogName}Descriptor.Instance);");
            }
        }

        sb.AppendLine();
        sb.AppendLine("            return registry;");
        sb.AppendLine("        }");
        sb.AppendLine("    }");
        sb.AppendLine("}");

        context.AddSource("GeneratedAuditRegistryExtensions.g.cs", sb.ToString());
    }

    public static void GenerateModelBuilderExtension(SourceProductionContext context, ImmutableArray<ConfiguratorInfo> configurators)
    {
        var ns = Helpers.GetNs(configurators[0]);
        var sb = new StringBuilder();
        sb.AppendLine("// <auto-generated />");
        sb.AppendLine("#nullable enable");
        sb.AppendLine();
        sb.AppendLine("using Microsoft.EntityFrameworkCore;");
        sb.AppendLine();
        sb.AppendLine($"namespace {ns}");
        sb.AppendLine("{");
        sb.AppendLine("    public static partial class GeneratedAuditModelBuilderExtensions");
        sb.AppendLine("    {");
        sb.AppendLine("        public static ModelBuilder ApplyGeneratedAuditMaps(this ModelBuilder modelBuilder)");
        sb.AppendLine("        {");

        foreach (var config in configurators)
        {
            sb.AppendLine($"            modelBuilder.ApplyConfiguration(new {config.AuditLogName}EntityMap());");
            foreach (var col in config.Collections)
                sb.AppendLine($"            modelBuilder.ApplyConfiguration(new {col.AuditLogName}EntityMap());");
        }

        sb.AppendLine();
        sb.AppendLine("            return modelBuilder;");
        sb.AppendLine("        }");
        sb.AppendLine("    }");
        sb.AppendLine("}");

        context.AddSource("GeneratedAuditModelBuilderExtensions.g.cs", sb.ToString());
    }
}
