#nullable enable
using Microsoft.CodeAnalysis;
using System.Text;

namespace AuditLog.Generator;

internal static class RootEntityGenerator
{
    public static void GenerateAuditLogClass(SourceProductionContext context, ConfiguratorInfo config)
    {
        var ns = Helpers.GetNs(config);
        var sb = new StringBuilder();
        sb.AppendLine("// <auto-generated />");
        sb.AppendLine("#nullable enable");
        sb.AppendLine();
        sb.AppendLine($"namespace {ns}");
        sb.AppendLine("{");
        sb.AppendLine($"    public sealed partial class {config.AuditLogName}");
        sb.AppendLine("    {");
        sb.AppendLine("        public long Id { get; set; }");
        sb.AppendLine();
        sb.AppendLine($"        public global::System.Guid {config.EntityName}Id {{ get; set; }}");
        sb.AppendLine();
        sb.AppendLine("        public string Operacao { get; set; } = null!;");
        sb.AppendLine();
        sb.AppendLine("        public global::System.DateTimeOffset OcorridoEm { get; set; }");
        sb.AppendLine();
        sb.AppendLine("        public string? UsuarioId { get; set; }");
        sb.AppendLine();
        sb.AppendLine("        public string? CorrelationId { get; set; }");
        sb.AppendLine();
        sb.AppendLine("        public string? CamposAlteradosJson { get; set; }");
        Helpers.BuildProperties(sb, config.Properties, config.EntityName);
        sb.AppendLine("    }");
        sb.AppendLine("}");

        context.AddSource($"{ns}.{config.AuditLogName}.g.cs", sb.ToString());
    }

    public static void GenerateEntityMapClass(SourceProductionContext context, ConfiguratorInfo config)
    {
        var ns = Helpers.GetNs(config);
        var sb = new StringBuilder();
        sb.AppendLine("// <auto-generated />");
        sb.AppendLine("#nullable enable");
        sb.AppendLine();
        sb.AppendLine("using Microsoft.EntityFrameworkCore;");
        sb.AppendLine("using Microsoft.EntityFrameworkCore.Metadata.Builders;");
        sb.AppendLine();
        sb.AppendLine($"namespace {ns}");
        sb.AppendLine("{");
        sb.AppendLine($"    public sealed class {config.AuditLogName}EntityMap");
        sb.AppendLine($"        : IEntityTypeConfiguration<{config.AuditLogName}>");
        sb.AppendLine("    {");
        sb.AppendLine($"        public void Configure(EntityTypeBuilder<{config.AuditLogName}> builder)");
        sb.AppendLine("        {");
        sb.AppendLine($"            builder.ToTable(\"{config.AuditLogName}s\");");
        sb.AppendLine();
        sb.AppendLine("            builder.HasKey(x => x.Id);");
        sb.AppendLine();
        sb.AppendLine("            builder.Property(x => x.Operacao)");
        sb.AppendLine("                .HasMaxLength(30)");
        sb.AppendLine("                .IsRequired();");
        sb.AppendLine();
        sb.AppendLine("            builder.Property(x => x.UsuarioId)");
        sb.AppendLine("                .HasMaxLength(100);");
        sb.AppendLine();
        sb.AppendLine("            builder.Property(x => x.CorrelationId)");
        sb.AppendLine("                .HasMaxLength(100);");
        sb.AppendLine();
        Helpers.BuildEntityMapProperties(sb, config.Properties);
        sb.AppendLine("            builder.HasIndex(x => new");
        sb.AppendLine("            {");
        sb.AppendLine($"                x.{config.EntityName}Id,");
        sb.AppendLine("                x.OcorridoEm");
        sb.AppendLine("            });");
        sb.AppendLine("        }");
        sb.AppendLine("    }");
        sb.AppendLine("}");

        context.AddSource($"{ns}.{config.AuditLogName}EntityMap.g.cs", sb.ToString());
    }

    public static void GenerateDescriptorClass(SourceProductionContext context, ConfiguratorInfo config)
    {
        var ns = Helpers.GetNs(config);
        var sb = new StringBuilder();
        sb.AppendLine("// <auto-generated />");
        sb.AppendLine("#nullable enable");
        sb.AppendLine();
        sb.AppendLine("using System;");
        sb.AppendLine("using System.Collections.Generic;");
        sb.AppendLine("using System.Text.Json;");
        sb.AppendLine("using AuditLog.Abstractions;");
        sb.AppendLine("using Microsoft.EntityFrameworkCore;");
        sb.AppendLine("using Microsoft.EntityFrameworkCore.ChangeTracking;");
        sb.AppendLine();
        sb.AppendLine($"namespace {ns}");
        sb.AppendLine("{");
        sb.AppendLine($"    public sealed class {config.AuditLogName}Descriptor");
        sb.AppendLine($"        : IAuditDescriptor<{config.EntityName}, {config.AuditLogName}>");
        sb.AppendLine("    {");
        sb.AppendLine($"        public static readonly {config.AuditLogName}Descriptor Instance = new();");
        sb.AppendLine();
        sb.AppendLine($"        private {config.AuditLogName}Descriptor()");
        sb.AppendLine("        {");
        sb.AppendLine("        }");
        sb.AppendLine();
        sb.AppendLine($"        public {config.AuditLogName} CreateLog(");
        sb.AppendLine($"            EntityEntry<{config.EntityName}> entry,");
        sb.AppendLine("            AuditExecutionContext context)");
        sb.AppendLine("        {");
        sb.AppendLine("            var entity = entry.Entity;");
        sb.AppendLine();
        sb.AppendLine($"            return new {config.AuditLogName}");
        sb.AppendLine("            {");
        sb.AppendLine($"                {config.EntityName}Id = entity.Id,");
        sb.AppendLine("                Operacao = entry.State.ToString(),");
        sb.AppendLine("                OcorridoEm = context.OcorridoEm,");
        sb.AppendLine("                UsuarioId = context.UsuarioId,");
        sb.AppendLine("                CorrelationId = context.CorrelationId,");
        sb.AppendLine();
        Helpers.BuildDescriptorAssignments(sb, config.Properties, "                ");
        sb.AppendLine();
        sb.AppendLine("                CamposAlteradosJson = BuildChangedPropertiesJson(entry)");
        sb.AppendLine("            };");
        sb.AppendLine("        }");
        sb.AppendLine();
        sb.AppendLine($"        public IReadOnlyList<{config.AuditLogName}> CreateChildLogs(");
        sb.AppendLine($"            EntityEntry<{config.EntityName}> entry,");
        sb.AppendLine("            AuditExecutionContext context)");
        sb.AppendLine("        {");
        sb.AppendLine($"            return global::System.Array.Empty<{config.AuditLogName}>();");
        sb.AppendLine("        }");
        sb.AppendLine();
        sb.AppendLine("        private static string BuildChangedPropertiesJson(");
        sb.AppendLine($"            EntityEntry<{config.EntityName}> entry)");
        sb.AppendLine("        {");
        sb.AppendLine("            var changed = new List<string>();");
        sb.AppendLine();
        sb.AppendLine("            if (entry.State is EntityState.Added or EntityState.Deleted)");
        sb.AppendLine("            {");
        sb.AppendLine("                changed.Add(\"*\");");
        sb.AppendLine("                return JsonSerializer.Serialize(changed);");
        sb.AppendLine("            }");
        sb.AppendLine();
        Helpers.BuildChangedPropertiesCheck(sb, config.Properties, config.EntityName);
        sb.AppendLine();
        sb.AppendLine("            return JsonSerializer.Serialize(changed);");
        sb.AppendLine("        }");
        sb.AppendLine("    }");
        sb.AppendLine("}");

        context.AddSource($"{ns}.{config.AuditLogName}Descriptor.g.cs", sb.ToString());
    }
}
