#nullable enable
using AuditLog.Generator;
using Microsoft.CodeAnalysis;
using System.Collections.Generic;
using System.Collections.Immutable;
using System.Linq;
using System.Text;

namespace AuditLog.Generator.SoftDelete;

internal static class HandlerGenerator
{
    public static void GenerateHandlerClass(SourceProductionContext context, EntityInfo entity, string dbContextFullName)
    {
        var ns = dbContextFullName.Contains(".") && !dbContextFullName.StartsWith("<")
            ? dbContextFullName.Substring(0, dbContextFullName.LastIndexOf('.'))
            : (entity.Namespace.StartsWith("<") ? "" : entity.Namespace);
        var sb = new StringBuilder();

        if (!string.IsNullOrEmpty(ns))
            sb.AppendLine($"namespace {ns};");
        sb.AppendLine("// <auto-generated />");
        sb.AppendLine("#nullable enable");
        sb.AppendLine();
        var usedNamespaces = new HashSet<string>();
        if (!string.IsNullOrEmpty(entity.Namespace) && !entity.Namespace.StartsWith("<"))
            usedNamespaces.Add(entity.Namespace);
        foreach (var fk in entity.ReferencingFks)
        {
            var depNs = ExtractNamespace(fk.DependentEntityFullName);
            if (!string.IsNullOrEmpty(depNs))
                usedNamespaces.Add(depNs);
        }
        foreach (var nsImport in usedNamespaces.OrderBy(x => x))
            sb.AppendLine($"using {nsImport};");
        sb.AppendLine("using Microsoft.EntityFrameworkCore;");
        sb.AppendLine("using AuditLog.EntityFrameworkCore.SoftDelete;");
        sb.AppendLine();
        sb.AppendLine($"public class {entity.Name}SoftDeleteHandler : ISoftDeleteHandler<{entity.FullName}>");
        sb.AppendLine("{");

        var hasCascade = false;
        var hasRestrict = false;
        var hasSetNull = false;

        foreach (var fk in entity.ReferencingFks)
        {
            if (fk.IsOwnership) continue;
            switch (fk.DeleteBehavior)
            {
                case "Cascade": hasCascade = true; break;
                case "Restrict": hasRestrict = true; break;
                case "SetNull": hasSetNull = true; break;
            }
        }

        // HandleDeleteAsync
        StringBuilderExtensions.AppendLine(sb, 1, $"public async System.Threading.Tasks.Task HandleDeleteAsync(DbContext ctx, {entity.FullName} entity, System.DateTime deletedAt)");
        StringBuilderExtensions.AppendLine(sb, 1, "{");

        if (hasRestrict)
        {
            StringBuilderExtensions.AppendLine(sb, 2, $"if (await ExistsRestrictAsync(ctx, entity.{entity.PrimaryKeyName}))");
            StringBuilderExtensions.AppendLine(sb, 3, $"throw new RestrictDeleteViolationException(\"{entity.Name}\", [entity.{entity.PrimaryKeyName}]);");
            sb.AppendLine();
        }

        if (hasSetNull)
        {
            StringBuilderExtensions.AppendLine(sb, 2, $"await HandleSetNullAsync(ctx, entity.{entity.PrimaryKeyName});");
        }

        if (hasCascade)
        {
            StringBuilderExtensions.AppendLine(sb, 2, "var visited = new System.Collections.Generic.HashSet<object>();");
            StringBuilderExtensions.AppendLine(sb, 2, $"await HandleCascadeAsync(ctx, entity.{entity.PrimaryKeyName}, deletedAt, visited);");
        }

        StringBuilderExtensions.AppendLine(sb, 1, "}");
        sb.AppendLine();

        // MarkDeleted (used for cascade dependents)
        StringBuilderExtensions.AppendLine(sb, 1, $"internal static void MarkDeleted(DbContext ctx, {entity.FullName} entity, System.DateTime deletedAt)");
        StringBuilderExtensions.AppendLine(sb, 1, "{");
        StringBuilderExtensions.AppendLine(sb, 2, "SoftDeleteInterceptor.MarkSoftDeleted(ctx.Entry(entity), deletedAt);");
        StringBuilderExtensions.AppendLine(sb, 1, "}");
        sb.AppendLine();

        // HandleSetNullAsync
        if (hasSetNull)
        {
            StringBuilderExtensions.AppendLine(sb, 1, $"private static async System.Threading.Tasks.Task HandleSetNullAsync(");
            StringBuilderExtensions.AppendLine(sb, 2, $"DbContext context, {entity.PrimaryKeyType} {FirstLower(entity.PrimaryKeyName)})");
            StringBuilderExtensions.AppendLine(sb, 1, "{");

            foreach (var fk in entity.ReferencingFks)
            {
                if (fk.IsOwnership || fk.DeleteBehavior != "SetNull") continue;
                sb.AppendLine();
                var listName = $"{FirstLower(fk.DependentEntityName)}{fk.FkPropertyName}NullList";
                StringBuilderExtensions.AppendLine(sb, 2, $"// SetNull: {fk.DependentEntityName}.{fk.FkPropertyName} -> null");
                StringBuilderExtensions.AppendLine(sb, 2, $"var {listName} = await context.Set<{fk.DependentEntityFullName}>()");
                StringBuilderExtensions.AppendLine(sb, 3, ".IgnoreQueryFilters()");
                StringBuilderExtensions.AppendLine(sb, 3, $".Where(x => x.{fk.FkPropertyName} == {FirstLower(entity.PrimaryKeyName)}).ToListAsync();");
                sb.AppendLine();
                StringBuilderExtensions.AppendLine(sb, 2, $"foreach (var d in {listName})");
                StringBuilderExtensions.AppendLine(sb, 2, "{");
                StringBuilderExtensions.AppendLine(sb, 3, $"d.{fk.FkPropertyName} = null;");
                StringBuilderExtensions.AppendLine(sb, 2, "}");
            }

            StringBuilderExtensions.AppendLine(sb, 1, "}");
            sb.AppendLine();
        }

        // HandleCascadeAsync
        StringBuilderExtensions.AppendLine(sb, 1, $"internal static async System.Threading.Tasks.Task HandleCascadeAsync(");
        StringBuilderExtensions.AppendLine(sb, 2, $"DbContext context, {entity.PrimaryKeyType} {FirstLower(entity.PrimaryKeyName)}, System.DateTime deletedAt, System.Collections.Generic.HashSet<object> visited)");
        StringBuilderExtensions.AppendLine(sb, 1, "{");

        foreach (var fk in entity.ReferencingFks)
        {
            if (fk.IsOwnership || fk.DeleteBehavior != "Cascade") continue;
            sb.AppendLine();
            var listName = $"{FirstLower(fk.DependentEntityName)}{fk.FkPropertyName}List";
            StringBuilderExtensions.AppendLine(sb, 2, $"// Cascade: {fk.DependentEntityName}.{fk.FkPropertyName} -> {entity.Name}.{entity.PrimaryKeyName}");
            StringBuilderExtensions.AppendLine(sb, 2, $"var {listName} = await context.Set<{fk.DependentEntityFullName}>()");
            StringBuilderExtensions.AppendLine(sb, 3, ".IgnoreQueryFilters()");
            StringBuilderExtensions.AppendLine(sb, 3, $".Where(x => x.{fk.FkPropertyName} == {FirstLower(entity.PrimaryKeyName)}).ToListAsync();");
            sb.AppendLine();
            StringBuilderExtensions.AppendLine(sb, 2, $"foreach (var d in {listName})");
            StringBuilderExtensions.AppendLine(sb, 2, "{");
            StringBuilderExtensions.AppendLine(sb, 3, "if (visited.Add(d))");
            StringBuilderExtensions.AppendLine(sb, 3, "{");
            if (fk.DependentIsSoftDelete)
            {
                StringBuilderExtensions.AppendLine(sb, 4, $"{fk.DependentEntityName}SoftDeleteHandler.MarkDeleted(context, d, deletedAt);");
                StringBuilderExtensions.AppendLine(sb, 4, $"await {fk.DependentEntityName}SoftDeleteHandler.HandleCascadeAsync(context, d.{fk.DependentPkName}, deletedAt, visited);");
            }
            else
            {
                StringBuilderExtensions.AppendLine(sb, 4, "context.Entry(d).State = Microsoft.EntityFrameworkCore.EntityState.Deleted;");
            }
            StringBuilderExtensions.AppendLine(sb, 3, "}");
            StringBuilderExtensions.AppendLine(sb, 2, "}");
        }

        StringBuilderExtensions.AppendLine(sb, 1, "}");
        sb.AppendLine();

        // ExistsRestrictAsync
        if (hasRestrict)
        {
            StringBuilderExtensions.AppendLine(sb, 1, $"private static async System.Threading.Tasks.Task<bool> ExistsRestrictAsync(");
            StringBuilderExtensions.AppendLine(sb, 2, $"DbContext context, {entity.PrimaryKeyType} {FirstLower(entity.PrimaryKeyName)})");
            StringBuilderExtensions.AppendLine(sb, 1, "{");

            var restrictFks = entity.ReferencingFks.Where(fk => !fk.IsOwnership && fk.DeleteBehavior == "Restrict").ToImmutableArray();

            if (restrictFks.Length == 0)
            {
                StringBuilderExtensions.AppendLine(sb, 2, "return false;");
            }
            else if (restrictFks.Length == 1)
            {
                var fk = restrictFks[0];
                StringBuilderExtensions.AppendLine(sb, 2, $"return await context.Set<{fk.DependentEntityFullName}>()");
                StringBuilderExtensions.AppendLine(sb, 3, ".IgnoreQueryFilters()");
                StringBuilderExtensions.AppendLine(sb, 3, $".AnyAsync(x => x.{fk.FkPropertyName} == {FirstLower(entity.PrimaryKeyName)});");
            }
            else
            {
                var first = true;
                foreach (var fk in restrictFks)
                {
                    if (first)
                    {
                        StringBuilderExtensions.AppendIndent(sb, 2);
                        sb.Append("return ");
                        first = false;
                    }
                    else
                    {
                        sb.AppendLine();
                        StringBuilderExtensions.AppendIndent(sb, 4);
                        sb.Append("|| ");
                    }
                    sb.AppendLine($"await context.Set<{fk.DependentEntityFullName}>()");
                    StringBuilderExtensions.AppendLine(sb, 5, ".IgnoreQueryFilters()");
                    StringBuilderExtensions.AppendIndent(sb, 5);
                    sb.Append($".AnyAsync(x => x.{fk.FkPropertyName} == {FirstLower(entity.PrimaryKeyName)})");
                }
                sb.AppendLine(";");
            }

            StringBuilderExtensions.AppendLine(sb, 1, "}");
        }

        sb.AppendLine("}");

        SourceProductionContextExtensions.AddHintSource(context, ns, $"{entity.Name}SoftDeleteHandler.g.cs", sb.ToString());
    }

    private static string FirstLower(string s)
        => s.Length > 0 ? char.ToLowerInvariant(s[0]) + s.Substring(1) : s;

    private static string ExtractNamespace(string fullName)
    {
        var lastDot = fullName.LastIndexOf('.');
        return lastDot > 0 ? fullName.Substring(0, lastDot) : "";
    }
}
