#nullable enable
using AuditLog.Generator;
using Microsoft.CodeAnalysis;
using System.Collections.Immutable;
using System.Linq;
using System.Text;

namespace AuditLog.Generator.SoftDelete;

internal static class HandlerGenerator
{
    public static void GenerateHandlerClass(SourceProductionContext context, EntityInfo entity, string dbContextFullName)
    {
        var ns = entity.Namespace;
        var sb = new StringBuilder();

        StringBuilderExtensions.AppendAutoGeneratedHeader(sb, ns);
        sb.AppendLine("using Microsoft.EntityFrameworkCore;");
        sb.AppendLine("using AuditLog.EntityFrameworkCore.SoftDelete;");
        sb.AppendLine();
        sb.AppendLine($"public class {entity.Name}SoftDeleteHandler : ISoftDeleteHandler<{entity.FullName}>");
        sb.AppendLine("{");

        var hasCascade = false;
        var hasRestrict = false;
        var hasSetNull = false;

        foreach (var fk in entity.ReferencingFks)
        {
            if (fk.IsOwnership) continue;
            switch (fk.DeleteBehavior)
            {
                case "Cascade": hasCascade = true; break;
                case "Restrict": hasRestrict = true; break;
                case "SetNull": hasSetNull = true; break;
            }
        }

        // HandleDeleteAsync
        StringBuilderExtensions.AppendLine(sb, 1, $"public async System.Threading.Tasks.Task HandleDeleteAsync(DbContext ctx, {entity.FullName} entity, System.DateTime deletedAt)");
        StringBuilderExtensions.AppendLine(sb, 1, "{");
        sb.AppendLine();

        if (hasRestrict)
        {
            foreach (var fk in entity.ReferencingFks)
            {
                if (fk.IsOwnership || fk.DeleteBehavior != "Restrict") continue;
                StringBuilderExtensions.AppendLine(sb, 2, $"if (await ctx.Set<{fk.DependentEntityFullName}>().IgnoreQueryFilters().AnyAsync(x => x.{fk.FkPropertyName} == entity.{entity.PrimaryKeyName}))");
                StringBuilderExtensions.AppendLine(sb, 3, $"throw new RestrictDeleteViolationException(\"{entity.Name}\", [entity.{entity.PrimaryKeyName}]);");
            }
        }

        if (hasCascade || hasSetNull)
        {
            sb.AppendLine();
            StringBuilderExtensions.AppendLine(sb, 2, "var visited = new System.Collections.Generic.HashSet<object>();");
            StringBuilderExtensions.AppendLine(sb, 2, $"await HandleCascadeAsync(ctx, entity.{entity.PrimaryKeyName}, deletedAt, visited);");
        }

        StringBuilderExtensions.AppendLine(sb, 1, "}");
        sb.AppendLine();

        // MarkDeleted (used for cascade dependents)
        StringBuilderExtensions.AppendLine(sb, 1, $"public static void MarkDeleted(DbContext ctx, {entity.FullName} entity, System.DateTime deletedAt)");
        StringBuilderExtensions.AppendLine(sb, 1, "{");
        StringBuilderExtensions.AppendLine(sb, 2, "SoftDeleteInterceptor.MarkSoftDeleted(ctx.Entry(entity), deletedAt);");
        StringBuilderExtensions.AppendLine(sb, 1, "}");
        sb.AppendLine();

        // HandleCascadeAsync
        StringBuilderExtensions.AppendLine(sb, 1, $"public static async System.Threading.Tasks.Task HandleCascadeAsync(");
        StringBuilderExtensions.AppendLine(sb, 2, $"DbContext context, {entity.PrimaryKeyType} {FirstLower(entity.PrimaryKeyName)}, System.DateTime deletedAt, System.Collections.Generic.HashSet<object> visited)");
        StringBuilderExtensions.AppendLine(sb, 1, "{");

        foreach (var fk in entity.ReferencingFks)
        {
            if (fk.IsOwnership) continue;

            switch (fk.DeleteBehavior)
            {
                case "Cascade":
                    sb.AppendLine();
                    StringBuilderExtensions.AppendLine(sb, 2, $"// Cascade: {fk.DependentEntityName}.{fk.FkPropertyName} -> {entity.Name}.{entity.PrimaryKeyName}");
                    StringBuilderExtensions.AppendLine(sb, 2, $"var {FirstLower(fk.DependentEntityName)}List = await context.Set<{fk.DependentEntityFullName}>()");
                    StringBuilderExtensions.AppendLine(sb, 3, ".IgnoreQueryFilters()");
                    StringBuilderExtensions.AppendLine(sb, 3, $".Where(x => x.{fk.FkPropertyName} == {FirstLower(entity.PrimaryKeyName)}).ToListAsync();");
                    sb.AppendLine();
                    StringBuilderExtensions.AppendLine(sb, 2, $"foreach (var d in {FirstLower(fk.DependentEntityName)}List)");
                    StringBuilderExtensions.AppendLine(sb, 2, "{");
                    StringBuilderExtensions.AppendLine(sb, 3, "if (visited.Add(d))");
                    StringBuilderExtensions.AppendLine(sb, 3, "{");
                    if (fk.DependentIsSoftDelete)
                    {
                        StringBuilderExtensions.AppendLine(sb, 4, $"{fk.DependentEntityName}SoftDeleteHandler.MarkDeleted(context, d, deletedAt);");
                        StringBuilderExtensions.AppendLine(sb, 4, $"await {fk.DependentEntityName}SoftDeleteHandler.HandleCascadeAsync(context, d.{fk.FkPropertyName}!, deletedAt, visited);");
                    }
                    else
                    {
                        StringBuilderExtensions.AppendLine(sb, 4, "context.Entry(d).State = Microsoft.EntityFrameworkCore.EntityState.Deleted;");
                    }
                    StringBuilderExtensions.AppendLine(sb, 3, "}");
                    StringBuilderExtensions.AppendLine(sb, 2, "}");
                    break;

                case "SetNull":
                    sb.AppendLine();
                    StringBuilderExtensions.AppendLine(sb, 2, $"// SetNull: {fk.DependentEntityName}.{fk.FkPropertyName} -> null");
                    StringBuilderExtensions.AppendLine(sb, 2, $"var {FirstLower(fk.DependentEntityName)}NullList = await context.Set<{fk.DependentEntityFullName}>()");
                    StringBuilderExtensions.AppendLine(sb, 3, ".IgnoreQueryFilters()");
                    StringBuilderExtensions.AppendLine(sb, 3, $".Where(x => x.{fk.FkPropertyName} == {FirstLower(entity.PrimaryKeyName)}).ToListAsync();");
                    sb.AppendLine();
                    StringBuilderExtensions.AppendLine(sb, 2, $"foreach (var d in {FirstLower(fk.DependentEntityName)}NullList)");
                    StringBuilderExtensions.AppendLine(sb, 2, "{");
                    StringBuilderExtensions.AppendLine(sb, 3, $"d.{fk.FkPropertyName} = null;");
                    StringBuilderExtensions.AppendLine(sb, 2, "}");
                    break;
            }
        }

        StringBuilderExtensions.AppendLine(sb, 1, "}");

        if (hasRestrict)
        {
            sb.AppendLine();
            StringBuilderExtensions.AppendLine(sb, 1, $"public static async System.Threading.Tasks.Task<bool> ExistsRestrictAsync(");
            StringBuilderExtensions.AppendLine(sb, 2, $"DbContext context, {entity.PrimaryKeyType} {FirstLower(entity.PrimaryKeyName)})");
            StringBuilderExtensions.AppendLine(sb, 1, "{");

            var restrictFks = entity.ReferencingFks.Where(fk => !fk.IsOwnership && fk.DeleteBehavior == "Restrict").ToImmutableArray();

            if (restrictFks.Length == 0)
            {
                StringBuilderExtensions.AppendLine(sb, 2, "return false;");
            }
            else if (restrictFks.Length == 1)
            {
                var fk = restrictFks[0];
                StringBuilderExtensions.AppendLine(sb, 2, $"return await context.Set<{fk.DependentEntityFullName}>()");
                StringBuilderExtensions.AppendLine(sb, 3, ".IgnoreQueryFilters()");
                StringBuilderExtensions.AppendLine(sb, 3, $".AnyAsync(x => x.{fk.FkPropertyName} == {FirstLower(entity.PrimaryKeyName)});");
            }
            else
            {
                var first = true;
                foreach (var fk in restrictFks)
                {
                    if (first)
                    {
                        StringBuilderExtensions.AppendIndent(sb, 2);
                        sb.Append("return ");
                        first = false;
                    }
                    else
                    {
                        sb.AppendLine();
                        StringBuilderExtensions.AppendIndent(sb, 4);
                        sb.Append("|| ");
                    }
                    sb.AppendLine($"await context.Set<{fk.DependentEntityFullName}>()");
                    StringBuilderExtensions.AppendLine(sb, 5, ".IgnoreQueryFilters()");
                    StringBuilderExtensions.AppendIndent(sb, 5);
                    sb.Append($".AnyAsync(x => x.{fk.FkPropertyName} == {FirstLower(entity.PrimaryKeyName)})");
                }
                sb.AppendLine(";");
            }

            StringBuilderExtensions.AppendLine(sb, 1, "}");
        }

        sb.AppendLine("}");

        SourceProductionContextExtensions.AddHintSource(context, ns, $"{entity.Name}SoftDeleteHandler.g.cs", sb.ToString());
    }

    private static string FirstLower(string s)
        => s.Length > 0 ? char.ToLowerInvariant(s[0]) + s.Substring(1) : s;
}
