#nullable enable
using AuditLog.Generator;
using Microsoft.CodeAnalysis;
using System.Collections.Immutable;
using System.Text;

namespace AuditLog.Generator.SoftDelete;

internal static class RegistryGenerator
{
    public static void GenerateRegistryExtension(
        SourceProductionContext context,
        ImmutableArray<EntityInfo> entities,
        string dbContextFullName)
    {
        var ns = entities.Length > 0 ? entities[0].Namespace : "AuditLog.Generated";
        var sb = new StringBuilder();

        StringBuilderExtensions.AppendAutoGeneratedHeader(sb, ns);
        sb.AppendLine("using AuditLog.EntityFrameworkCore.SoftDelete;");
        sb.AppendLine();
        sb.AppendLine("public static class GeneratedSoftDeleteRegistryExtensions");
        sb.AppendLine("{");
        StringBuilderExtensions.AppendLine(sb, 1, $"public static SoftDeleteHandlerRegistry AddGeneratedSoftDeleteHandlers(this SoftDeleteHandlerRegistry registry)");
        StringBuilderExtensions.AppendLine(sb, 1, "{");

        foreach (var entity in entities)
        {
            if (!entity.IsSoftDelete) continue;
            StringBuilderExtensions.AppendLine(sb, 2, $"registry.Register(typeof({entity.FullName}), new {entity.Name}SoftDeleteHandler());");
        }

        StringBuilderExtensions.AppendLine(sb, 2, "return registry;");
        StringBuilderExtensions.AppendLine(sb, 1, "}");

        sb.AppendLine("}");

        SourceProductionContextExtensions.AddHintSource(context, ns, "GeneratedSoftDeleteRegistryExtensions.g.cs", sb.ToString());
    }
}
