#nullable enable
using AuditLog.Generator;
using Microsoft.CodeAnalysis;
using System.Collections.Immutable;
using System.Text;

namespace AuditLog.Generator.SoftDelete;

internal static class RegistryGenerator
{
    public static void GenerateRegistryExtension(
        SourceProductionContext context,
        ImmutableArray<EntityInfo> entities,
        string dbContextFullName)
    {
        var ns = dbContextFullName.Contains(".") && !dbContextFullName.StartsWith("<")
            ? dbContextFullName.Substring(0, dbContextFullName.LastIndexOf('.'))
            : (entities.Length > 0 && !entities[0].Namespace.StartsWith("<") ? entities[0].Namespace : "");
        var sb = new StringBuilder();

        if (!string.IsNullOrEmpty(ns))
            sb.AppendLine($"namespace {ns};");
        sb.AppendLine("// <auto-generated />");
        sb.AppendLine("#nullable enable");
        sb.AppendLine();
        sb.AppendLine("using AuditLog.EntityFrameworkCore.SoftDelete;");
        sb.AppendLine();
        sb.AppendLine("public static class GeneratedSoftDeleteRegistryExtensions");
        sb.AppendLine("{");
        StringBuilderExtensions.AppendLine(sb, 1, $"public static SoftDeleteHandlerRegistry AddGeneratedSoftDeleteHandlers(this SoftDeleteHandlerRegistry registry)");
        StringBuilderExtensions.AppendLine(sb, 1, "{");

        foreach (var entity in entities)
        {
            if (!entity.IsSoftDelete) continue;
            StringBuilderExtensions.AppendLine(sb, 2, $"registry.Register(typeof({entity.FullName}), new {entity.Name}SoftDeleteHandler());");
        }

        StringBuilderExtensions.AppendLine(sb, 2, "return registry;");
        StringBuilderExtensions.AppendLine(sb, 1, "}");

        sb.AppendLine("}");

        SourceProductionContextExtensions.AddHintSource(context, ns, "GeneratedSoftDeleteRegistryExtensions.g.cs", sb.ToString());
    }
}
